import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import AnalyticsChart from './analytics-chart'
import { Activity, Users, Calendar as CalendarIcon, Clock } from 'lucide-react'
import { useState } from 'react'
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { format, subDays } from 'date-fns'
import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/button'
import { Calendar } from '@/components/ui/calendar'
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover'
import { DateRange } from 'react-day-picker'
import ShiftChart from './shift-chart'
import { motion } from 'framer-motion'

interface AnalyticsProps {
  users: any[]
}

export function Analytics({ users }: AnalyticsProps) {
  const [granularity, setGranularity] = useState<'day' | 'week' | 'month'>('day')
  const [dateRange, setDateRange] = useState<DateRange | undefined>({
    from: subDays(new Date(), 7),
    to: new Date(),
  })

  const container = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1
      }
    }
  }

  const item = {
    hidden: { opacity: 0, y: 20 },
    show: { opacity: 1, y: 0 }
  }

  return (
    <motion.div 
      variants={container}
      initial="hidden"
      animate="show"
      className='space-y-4'
    >
      <motion.div variants={item}>
        <Card className="hover:shadow-md transition-shadow duration-300">
          <CardHeader className='flex flex-row items-center justify-between'>
            <div>
              <CardTitle>Ticket Generation Analytics</CardTitle>
              <CardDescription>
                Breakdown of tickets generated by {granularity}.
              </CardDescription>
            </div>
            <div className="flex items-center gap-2">
              <div className={cn('grid gap-2')}>
                <Popover>
                  <PopoverTrigger asChild>
                    <Button
                      id='date'
                      variant={'outline'}
                      className={cn(
                        'w-[300px] justify-start text-left font-normal',
                        !dateRange && 'text-muted-foreground'
                      )}
                    >
                      <CalendarIcon className='mr-2 h-4 w-4' />
                      {dateRange?.from ? (
                        dateRange.to ? (
                          <>
                            {format(dateRange.from, 'LLL dd, y')} -{' '}
                            {format(dateRange.to, 'LLL dd, y')}
                          </>
                        ) : (
                          format(dateRange.from, 'LLL dd, y')
                        )
                      ) : (
                        <span>Pick a date range</span>
                      )}
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className='w-auto p-0' align='end'>
                    <Calendar
                      initialFocus
                      mode='range'
                      defaultMonth={dateRange?.from}
                      selected={dateRange}
                      onSelect={setDateRange}
                      numberOfMonths={2}
                    />
                  </PopoverContent>
                </Popover>
              </div>
              <Tabs value={granularity} onValueChange={(v) => setGranularity(v as 'day' | 'week' | 'month')}>
                <TabsList>
                  <TabsTrigger value='day'>Day</TabsTrigger>
                  <TabsTrigger value='week'>Week</TabsTrigger>
                  <TabsTrigger value='month'>Month</TabsTrigger>
                </TabsList>
              </Tabs>
            </div>
          </CardHeader>
          <CardContent className='px-6'>
            <AnalyticsChart users={users} granularity={granularity} dateRange={dateRange} />
          </CardContent>
        </Card>
      </motion.div>

      <div className='grid gap-4 md:grid-cols-2 lg:grid-cols-7'>
        <motion.div variants={item} className="col-span-4">
          <Card className="h-full hover:shadow-md transition-shadow duration-300">
            <CardHeader>
              <CardTitle>Production by Shift</CardTitle>
              <CardDescription>
                Ticket generation distribution across shifts (Morning, Afternoon, Night).
              </CardDescription>
            </CardHeader>
            <CardContent className="pl-2">
              <ShiftChart users={users} dateRange={dateRange} />
            </CardContent>
          </Card>
        </motion.div>
        <motion.div variants={item} className="col-span-3">
          <Card className="h-full hover:shadow-md transition-shadow duration-300">
             <CardHeader>
              <CardTitle>Key Metrics</CardTitle>
              <CardDescription>
                Summary of performance indicators.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-8">
              <div className="flex items-center">
                <div className="p-2 bg-blue-100 dark:bg-blue-900/20 rounded-full mr-4">
                  <Activity className='text-blue-600 dark:text-blue-400 h-4 w-4' />
                </div>
                <div className="space-y-1">
                  <p className="text-sm font-medium leading-none">Total Tickets</p>
                  <p className="text-sm text-muted-foreground">
                    {users.length} generated in selected period
                  </p>
                </div>
                <div className="ml-auto font-bold">
                  +{users.length}
                </div>
              </div>
               <div className="flex items-center">
                <div className="p-2 bg-green-100 dark:bg-green-900/20 rounded-full mr-4">
                  <Users className='text-green-600 dark:text-green-400 h-4 w-4' />
                </div>
                <div className="space-y-1">
                  <p className="text-sm font-medium leading-none">Active Generators</p>
                  <p className="text-sm text-muted-foreground">
                    Unique users active
                  </p>
                </div>
                <div className="ml-auto font-bold">
                  15
                </div>
              </div>
               <div className="flex items-center">
                <div className="p-2 bg-purple-100 dark:bg-purple-900/20 rounded-full mr-4">
                  <Clock className='text-purple-600 dark:text-purple-400 h-4 w-4' />
                </div>
                <div className="space-y-1">
                  <p className="text-sm font-medium leading-none">Avg. Time</p>
                  <p className="text-sm text-muted-foreground">
                    Per ticket generation
                  </p>
                </div>
                <div className="ml-auto font-bold">
                  1.2s
                </div>
              </div>
            </CardContent>
          </Card>
        </motion.div>
      </div>
    </motion.div>
  )
}

export default Analytics
